version: "3.4"

services:
  simbirhealth-account:
    container_name: simbirhealth-account
    hostname: simbirhealth-account
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: SimbirHealth.Account/Dockerfile
    ports:
    - "8080:8080"

  simbirhealth-hospital:
    container_name: simbirhealth-hospital
    hostname: simbirhealth-hospital
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: SimbirHealth.Hospital/Dockerfile
    ports:
    - "8081:8081"

  db:
    image: postgres:latest
    container_name: db
    hostname: db
    restart: always
    environment:
    - POSTGRES_DB=simbir_health
    - POSTGRES_USER=postgres  
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5434:5432"
    
        