services:
  simbirhealth-account:
    container_name: simbirhealth-account
    hostname: simbirhealth-account
    restart: always
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: SimbirHealth.Account/Dockerfile
    ports:
    - "8080:8080"

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simbir_health
    ports:
    - "5432:5432"
        